[package]
name = "chip8-emulator"
version = "0.1.0"
authors = ["Tiv0w <t.theomeyer@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2.2", features = ["js"] }
rand = "0.8.3"
wasm-bindgen = "0.2.73"
